// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Walkiria.Restrictions.DataContext;

#nullable disable

namespace Walkiria.Restrictions.DataContext.Migrations
{
    [DbContext(typeof(RestrictionDataContext))]
    partial class RestrictionDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Walkiria.Restrictions.DataContext.Models.Restriction", b =>
                {
                    b.Property<long>("UserTgId")
                        .HasColumnType("bigint");

                    b.Property<long>("GroupTgId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("TypeResctriction")
                        .HasColumnType("integer");

                    b.HasKey("UserTgId", "GroupTgId");

                    b.ToTable("Restrictions");
                });
#pragma warning restore 612, 618
        }
    }
}
