networks:
  walkiria.restrictions.web:
    driver: bridge
services:
  app:
    container_name: walkiria.restrictions
    build:
      context: .
      dockerfile: Walkiria.Restrictions.Web/Dockerfile
    ports:
      - "80:80"
    networks:
      - walkiria.restrictions.webapi
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: walkiria_restrictions
    ports:
      - "6432:6432"
    networks:
      - walkiria.restrictions.web
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: